import 'package:flutter/material.dart';

class ThemePalette {
  final String id;
  final String zhName;
  final String zhHantName;
  final String enName;
  final ColorScheme light;
  final ColorScheme dark;

  const ThemePalette({
    required this.id,
    required this.zhName,
    required this.zhHantName,
    required this.enName,
    required this.light,
    required this.dark,
  });

  String get displayNameZh => zhName;
  String get displayNameZhHant => zhHantName;
  String get displayNameEn => enName;

  String localizedName(BuildContext context) {
    final locale = Localizations.localeOf(context);
    if (locale.languageCode == 'zh') {
      if (locale.scriptCode == 'Hant' ||
          locale.countryCode == 'TW' ||
          locale.countryCode == 'HK' ||
          locale.countryCode == 'MO') {
        return zhHantName;
      }
      return zhName;
    }
    return enName;
  }
}

class ThemePalettes {
  static const String defaultId = 'blue';
  static const String blueId = 'blue';
  static const String monochromeId = 'monochrome';
  static const String minimalId = 'minimal';
  static const String vermillionId = 'vermillion';
  static const String amberId = 'amber';
  static const String greenId = 'green';

  // 1. 海霄藍 (Aether Blue)
  static const ThemePalette blue = ThemePalette(
    id: blueId,
    zhName: '海霄蓝',
    zhHantName: '海霄藍',
    enName: 'Aether Blue',
    light: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF3E5E98),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFD8E2FF),
      onPrimaryContainer: Color(0xFF001A43),
      secondary: Color(0xFF575E71),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFDBE2F9),
      onSecondaryContainer: Color(0xFF141B2C),
      tertiary: Color(0xFF715573),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFFBD7FC),
      onTertiaryContainer: Color(0xFF2A132D),
      error: Color(0xFFBA1A1A),
      onError: Color(0xFFFFFFFF),
      errorContainer: Color(0xFFFFDAD6),
      onErrorContainer: Color(0xFF410002),
      surface: Color(0xFFF7F7F7),
      onSurface: Color(0xFF202020),
      onSurfaceVariant: Color(0xFF646464),
      outline: Color(0x1A000000),
      outlineVariant: Color(0xFF000000),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFF121213),
      onInverseSurface: Color(0xFFF9F9F9),
      inversePrimary: Color(0xFFAEC6FF),
      surfaceTint: Color(0xFF3E5E98),
    ),
    dark: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFAEC6FF),
      onPrimary: Color(0xFF022F67),
      primaryContainer: Color(0xFF24467E),
      onPrimaryContainer: Color(0xFFD8E2FF),
      secondary: Color(0xFFBFC6DC),
      onSecondary: Color(0xFF293042),
      secondaryContainer: Color(0xFF3F4759),
      onSecondaryContainer: Color(0xFFDBE2F9),
      tertiary: Color(0xFFDEBCDF),
      onTertiary: Color(0xFF402843),
      tertiaryContainer: Color(0xFF583E5B),
      onTertiaryContainer: Color(0xFFFBD7FC),
      error: Color(0xFFFFB4AB),
      onError: Color(0xFF690005),
      errorContainer: Color(0xFF93000A),
      onErrorContainer: Color(0xFFFFDAD6),
      surface: Color(0xFF121213),
      onSurface: Color(0xFFF9F9F9),
      onSurfaceVariant: Color(0xFFCECECE),
      outline: Color(0x1A000000),
      outlineVariant: Color(0xFFFFFFFF),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFFF7F7F7),
      onInverseSurface: Color(0xFF202020),
      inversePrimary: Color(0xFF3E5E98),
      surfaceTint: Color(0xFFAEC6FF),
    ),
  );

  // 2. 紙墨灰 (Frost Gray)
  static const ThemePalette monochrome = ThemePalette(
    id: monochromeId,
    zhName: '纸墨灰',
    zhHantName: '紙墨灰',
    enName: 'Frost Gray',
    light: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF000000),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFEFEFEF),
      onPrimaryContainer: Color(0xFF000000),
      secondary: Color(0xFF1A1A1A),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFF4F4F4),
      onSecondaryContainer: Color(0xFF000000),
      tertiary: Color(0xFF2E2E2E),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFF7F7F7),
      onTertiaryContainer: Color(0xFF000000),
      error: Color(0xFF000000),
      onError: Color(0xFFFFFFFF),
      errorContainer: Color(0xFFEAEAEA),
      onErrorContainer: Color(0xFF000000),
      surface: Color(0xFFF7F7F7),
      onSurface: Color(0xFF202020),
      onSurfaceVariant: Color(0xFF646464),
      outline: Color(0x1A000000),
      outlineVariant: Color(0xFF000000),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFF121213),
      onInverseSurface: Color(0xFFF9F9F9),
      inversePrimary: Color(0xFFFFFFFF),
      surfaceTint: Color(0xFF000000),
    ),
    dark: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFFFFFFF),
      onPrimary: Color(0xFF000000),
      primaryContainer: Color(0xFF2B2B2B),
      onPrimaryContainer: Color(0xFFFFFFFF),
      secondary: Color(0xFFE0E0E0),
      onSecondary: Color(0xFF000000),
      secondaryContainer: Color(0xFF242424),
      onSecondaryContainer: Color(0xFFE0E0E0),
      tertiary: Color(0xFFCCCCCC),
      onTertiary: Color(0xFF000000),
      tertiaryContainer: Color(0xFF1F1F1F),
      onTertiaryContainer: Color(0xFFFFFFFF),
      error: Color(0xFFFFFFFF),
      onError: Color(0xFF000000),
      errorContainer: Color(0xFF333333),
      onErrorContainer: Color(0xFFFFFFFF),
      surface: Color(0xFF121213),
      onSurface: Color(0xFFF9F9F9),
      onSurfaceVariant: Color(0xFFCECECE),
      outline: Color(0x1A000000),
      outlineVariant: Color(0xFFFFFFFF),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFFF7F7F7),
      onInverseSurface: Color(0xFF202020),
      inversePrimary: Color(0xFF000000),
      surfaceTint: Color(0xFFFFFFFF),
    ),
  );

  // 3. 極簡藍 (Minimal Blue) - 移植自 RikkaHub MinimalTheme
  static const ThemePalette minimal = ThemePalette(
    id: minimalId,
    zhName: '极简蓝',
    zhHantName: '極簡藍',
    enName: 'Minimal Blue',
    light: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF2563EB),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFE7F0FE),
      onPrimaryContainer: Color(0xFF1B4ACB),
      secondary: Color(0xFF565A61),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFEFF0F2),
      onSecondaryContainer: Color(0xFF3B3E44),
      tertiary: Color(0xFF8A6A16),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFFCEFCE),
      onTertiaryContainer: Color(0xFF6A5008),
      error: Color(0xFFD93A32),
      onError: Color(0xFFFFFFFF),
      errorContainer: Color(0xFFFDE7E5),
      onErrorContainer: Color(0xFFA31710),
      surface: Color(0xFFFFFFFF),
      onSurface: Color(0xFF16181D),
      onSurfaceVariant: Color(0xFF6A6E75),
      outline: Color(0xFFC7CACF),
      outlineVariant: Color(0xFFE8E9EC),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFF2A2C31),
      onInverseSurface: Color(0xFFF3F4F6),
      inversePrimary: Color(0xFFAAC7FF),
      surfaceTint: Color(0xFF2563EB),
    ),
    dark: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFF8CB0FF),
      onPrimary: Color(0xFF082C6E),
      primaryContainer: Color(0xFF1D3E7F),
      onPrimaryContainer: Color(0xFFD9E4FF),
      secondary: Color(0xFFC3C6CC),
      onSecondary: Color(0xFF2B2E33),
      secondaryContainer: Color(0xFF3A3D43),
      onSecondaryContainer: Color(0xFFE2E4E8),
      tertiary: Color(0xFFE8CB84),
      onTertiary: Color(0xFF3F2E00),
      tertiaryContainer: Color(0xFF5B4400),
      onTertiaryContainer: Color(0xFFFFE6AA),
      error: Color(0xFFFFB4AB),
      onError: Color(0xFF690005),
      errorContainer: Color(0xFF93000A),
      onErrorContainer: Color(0xFFFFDAD6),
      surface: Color(0xFF0F1012),
      onSurface: Color(0xFFE6E7EA),
      onSurfaceVariant: Color(0xFFA0A4AB),
      outline: Color(0xFF4C4F55),
      outlineVariant: Color(0xFF2E3035),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFFE6E7EA),
      onInverseSurface: Color(0xFF2A2C31),
      inversePrimary: Color(0xFF2563EB),
      surfaceTint: Color(0xFF8CB0FF),
    ),
  );

  // 4. 硃砂紅 (Vermillion)
  static const ThemePalette vermillion = ThemePalette(
    id: vermillionId,
    zhName: '朱砂红',
    zhHantName: '硃砂紅',
    enName: 'Vermillion',
    light: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFFE03E2D),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFFFEDE9),
      onPrimaryContainer: Color(0xFF410002),
      secondary: Color(0xFF775651),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFFFDAD4),
      onSecondaryContainer: Color(0xFF2C1512),
      tertiary: Color(0xFF705C2E),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFFCE0A6),
      onTertiaryContainer: Color(0xFF261A00),
      error: Color(0xFFBA1A1A),
      onError: Color(0xFFFFFFFF),
      errorContainer: Color(0xFFFFDAD6),
      onErrorContainer: Color(0xFF410002),
      surface: Color(0xFFFFF8F7),
      onSurface: Color(0xFF231918),
      onSurfaceVariant: Color(0xFF534341),
      outline: Color(0xFF857370),
      outlineVariant: Color(0xFFD8C2BE),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFF392E2C),
      onInverseSurface: Color(0xFFFFEDE9),
      inversePrimary: Color(0xFFFFB4A7),
      surfaceTint: Color(0xFFE03E2D),
    ),
    dark: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFFFB4A7),
      onPrimary: Color(0xFF680007),
      primaryContainer: Color(0xFF93000E),
      onPrimaryContainer: Color(0xFFFFDAD4),
      secondary: Color(0xFFE7BDB6),
      onSecondary: Color(0xFF442925),
      secondaryContainer: Color(0xFF5D3F3B),
      onSecondaryContainer: Color(0xFFFFDAD4),
      tertiary: Color(0xFFDEC48C),
      onTertiary: Color(0xFF3E2E05),
      tertiaryContainer: Color(0xFF564419),
      onTertiaryContainer: Color(0xFFFCE0A6),
      error: Color(0xFFFFB4AB),
      onError: Color(0xFF690005),
      errorContainer: Color(0xFF93000A),
      onErrorContainer: Color(0xFFFFDAD6),
      surface: Color(0xFF1A1110),
      onSurface: Color(0xFFF1DFDC),
      onSurfaceVariant: Color(0xFFD8C2BE),
      outline: Color(0xFFA08C89),
      outlineVariant: Color(0xFF534341),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFFF1DFDC),
      onInverseSurface: Color(0xFF392E2C),
      inversePrimary: Color(0xFFB81D14),
      surfaceTint: Color(0xFFFFB4A7),
    ),
  );

  // 5. 琥珀金 (Amber)
  static const ThemePalette amber = ThemePalette(
    id: amberId,
    zhName: '琥珀金',
    zhHantName: '琥珀金',
    enName: 'Amber',
    light: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFFB45309),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFFEF3C7),
      onPrimaryContainer: Color(0xFF451A03),
      secondary: Color(0xFF715B2E),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFFDE8BA),
      onSecondaryContainer: Color(0xFF271900),
      tertiary: Color(0xFF4C662B),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFCDE8A3),
      onTertiaryContainer: Color(0xFF101F00),
      error: Color(0xFFBA1A1A),
      onError: Color(0xFFFFFFFF),
      errorContainer: Color(0xFFFFDAD6),
      onErrorContainer: Color(0xFF410002),
      surface: Color(0xFFFFFDF7),
      onSurface: Color(0xFF201B11),
      onSurfaceVariant: Color(0xFF4E4539),
      outline: Color(0xFF807567),
      outlineVariant: Color(0xFFD2C4B4),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFF363025),
      onInverseSurface: Color(0xFFFBEFE2),
      inversePrimary: Color(0xFFFFBA38),
      surfaceTint: Color(0xFFB45309),
    ),
    dark: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFFFBA38),
      onPrimary: Color(0xFF442B00),
      primaryContainer: Color(0xFF624000),
      onPrimaryContainer: Color(0xFFFFDF9E),
      secondary: Color(0xFFDEC38B),
      onSecondary: Color(0xFF3E2D04),
      secondaryContainer: Color(0xFF574319),
      onSecondaryContainer: Color(0xFFFDE8BA),
      tertiary: Color(0xFFB2CC89),
      onTertiary: Color(0xFF203602),
      tertiaryContainer: Color(0xFF354E15),
      onTertiaryContainer: Color(0xFFCDE8A3),
      error: Color(0xFFFFB4AB),
      onError: Color(0xFF690005),
      errorContainer: Color(0xFF93000A),
      onErrorContainer: Color(0xFFFFDAD6),
      surface: Color(0xFF17130B),
      onSurface: Color(0xFFEBE1D4),
      onSurfaceVariant: Color(0xFFD2C4B4),
      outline: Color(0xFF9B8F80),
      outlineVariant: Color(0xFF4E4539),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFFEBE1D4),
      onInverseSurface: Color(0xFF363025),
      inversePrimary: Color(0xFF825600),
      surfaceTint: Color(0xFFFFBA38),
    ),
  );

  // 6. 翡翠綠 (Emerald Green)
  static const ThemePalette green = ThemePalette(
    id: greenId,
    zhName: '翡翠绿',
    zhHantName: '翡翠綠',
    enName: 'Emerald Green',
    light: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF059669),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFD1FAE5),
      onPrimaryContainer: Color(0xFF022C22),
      secondary: Color(0xFF4D6357),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFD0E8D9),
      onSecondaryContainer: Color(0xFF0B1F16),
      tertiary: Color(0xFF3C6471),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFC0E9F9),
      onTertiaryContainer: Color(0xFF001F29),
      error: Color(0xFFBA1A1A),
      onError: Color(0xFFFFFFFF),
      errorContainer: Color(0xFFFFDAD6),
      onErrorContainer: Color(0xFF410002),
      surface: Color(0xFFF7FDF9),
      onSurface: Color(0xFF171D1A),
      onSurfaceVariant: Color(0xFF404943),
      outline: Color(0xFF707973),
      outlineVariant: Color(0xFFC0C9C2),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFF2C322E),
      onInverseSurface: Color(0xFFEEF2ED),
      inversePrimary: Color(0xFF6FDCB2),
      surfaceTint: Color(0xFF059669),
    ),
    dark: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFF6FDCB2),
      onPrimary: Color(0xFF003824),
      primaryContainer: Color(0xFF005136),
      onPrimaryContainer: Color(0xFF8CF8CD),
      secondary: Color(0xFFB4CCBD),
      onSecondary: Color(0xFF20352A),
      secondaryContainer: Color(0xFF364B40),
      onSecondaryContainer: Color(0xFFD0E8D9),
      tertiary: Color(0xFFA4CDDC),
      onTertiary: Color(0xFF053542),
      tertiaryContainer: Color(0xFF234C59),
      onTertiaryContainer: Color(0xFFC0E9F9),
      error: Color(0xFFFFB4AB),
      onError: Color(0xFF690005),
      errorContainer: Color(0xFF93000A),
      onErrorContainer: Color(0xFFFFDAD6),
      surface: Color(0xFF0F1512),
      onSurface: Color(0xFFDFE4DF),
      onSurfaceVariant: Color(0xFFC0C9C2),
      outline: Color(0xFF8A938C),
      outlineVariant: Color(0xFF404943),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFFDFE4DF),
      onInverseSurface: Color(0xFF2C322E),
      inversePrimary: Color(0xFF059669),
      surfaceTint: Color(0xFF6FDCB2),
    ),
  );

  static const List<ThemePalette> all = <ThemePalette>[
    blue,
    monochrome,
    minimal,
    vermillion,
    amber,
    green,
  ];

  static ThemePalette byId(String id) {
    return all.firstWhere(
      (p) => p.id == id,
      orElse: () => blue,
    );
  }
}
